#ifndef CHARACTERS_MOVEMENT_CONSTS_H__
#define CHARACTERS_MOVEMENT_CONSTS_H__

#define OGRE_STEP                2
#define SIMPLE_DIRECTIONS        4
#define DIAGONAL_DIRECTIONS      4
#define ALL_DIRECTIONS           8
#define SIMPLE_TO_DIAGONAL_SHIFT 4

#endif // CHARACTERS_MOVEMENT_CONSTS_H__
